apiVersion: apps/v1
kind: Deployment
metadata:
  name: profileservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profileservice
  template:
    metadata:
      labels:
        app: profileservice
    spec:
      containers:
      - name: profileservice
        image: fendamear/profileservice:latest
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: profileservice-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: profileservice
  ports:
  - name: profileservice
    protocol: TCP
    port: 80
    targetPort: 80