version: '3.4'

services:
  kweet:
    image: ${DOCKER_REGISTRY-}kweetservice
    ports: 
        - "5050:80"
    build: 
      context: .
      dockerfile: KweetService/Dockerfile     
    depends_on:
      - db
  Auth:
    image: ${DOCKER_REGISTRY-}authservice
    ports: 
        - "5051:80"
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example

