version: '3.4'

services:
  kweet:
    image: ${DOCKER_REGISTRY-}kweetservice
    ports: 
        - "5050:80"
    build: 
      context: .
      dockerfile: KweetService/Dockerfile     
    depends_on:
      - db
  Auth:
    image: ${DOCKER_REGISTRY-}authservice
    ports: 
        - "5051:80"
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    depends_on:
      - db
  Profile:
    image: ${DOCKER_REGISTRY-}profileservice
    ports: 
        - "5052:80"
    build:
      context: .
      dockerfile: ProfileService/Dockerfile
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
  db:
    image: mysql
    container_name: backend-db-1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
  rabbitmq:
        container_name: "rabbitmq"
        image: rabbitmq:3.8-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=myuser
            - RABBITMQ_DEFAULT_PASS=mypassword
        ports:
            # AMQP protocol port
            - '5672:5672'
            # HTTP management UI
            - '15672:15672'

