apiVersion: apps/v1
kind: Deployment
metadata:
  name: kweetservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kweetservice
  template:
    metadata:
      labels:
        app: kweetservice
    spec:
      containers:
      - name: kweetservice
        image: fendamear/kweetservice:latest
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: kweetservice-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: kweetservice
  ports:
  - name: kweetservice
    protocol: TCP
    port: 80
    targetPort: 80
