apiVersion: apps/v1
kind: Deployment
metadata:
  name: kweetservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kweetservice
  template:
    metadata:
      labels:
        app: kweetservice
    spec:
      containers:
      - name: kweetservice
        image: kweetservice
        imagePullPolicy: Never
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
