apiVersion: v1
kind: Service
metadata:
  name: kweetservicenp-srv
spec:
  type: NodePort
  selector:
    app: kweetservice
  ports:
    - name: kweetservice
      protocol: TCP
      port: 80
      targetPort: 80