// <auto-generated />
using System;
using Kweet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kweet.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Kweet.Models.KweetModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Kweets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9d382436-f61d-4f8f-aca4-265c3b058488"),
                            Date = new DateTime(2023, 5, 10, 14, 32, 41, 696, DateTimeKind.Local).AddTicks(4269),
                            IsEdited = false,
                            Message = "testMessage 1",
                            User = "User1"
                        },
                        new
                        {
                            Id = new Guid("6d237924-a3fe-454d-9d61-afa9359205c2"),
                            Date = new DateTime(2023, 5, 10, 14, 32, 41, 696, DateTimeKind.Local).AddTicks(4348),
                            IsEdited = true,
                            Message = "testMessage 2",
                            User = "User1"
                        },
                        new
                        {
                            Id = new Guid("9e7e04c6-692d-4f25-9ccc-6541acb9add8"),
                            Date = new DateTime(2023, 5, 10, 14, 32, 41, 696, DateTimeKind.Local).AddTicks(4373),
                            IsEdited = false,
                            Message = "testMessage 3",
                            User = "User1"
                        },
                        new
                        {
                            Id = new Guid("daf79d49-6e0d-44fc-942f-551b29025fba"),
                            Date = new DateTime(2023, 5, 10, 14, 32, 41, 696, DateTimeKind.Local).AddTicks(4385),
                            IsEdited = false,
                            Message = "testMessage 4",
                            User = "User1"
                        },
                        new
                        {
                            Id = new Guid("4d18d8b7-f3a6-4d78-80e0-768af0bbc19a"),
                            Date = new DateTime(2023, 5, 10, 14, 32, 41, 696, DateTimeKind.Local).AddTicks(4423),
                            IsEdited = true,
                            Message = "testMessage 5",
                            User = "User2"
                        },
                        new
                        {
                            Id = new Guid("09a6898f-f1b9-4d2c-9e68-c555ae1bd8ed"),
                            Date = new DateTime(2023, 5, 10, 14, 32, 41, 696, DateTimeKind.Local).AddTicks(4438),
                            IsEdited = false,
                            Message = "testMessage 6",
                            User = "User2"
                        });
                });

            modelBuilder.Entity("KweetService.Models.LikeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("KweetID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Likes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbd6fcd2-6022-46e6-9614-b173b0857865"),
                            KweetID = "9d382436-f61d-4f8f-aca4-265c3b058488",
                            UserID = "User2"
                        },
                        new
                        {
                            Id = new Guid("c905083a-0328-4f27-8992-7810dc15a28b"),
                            KweetID = "9d382436-f61d-4f8f-aca4-265c3b058488",
                            UserID = "User1"
                        },
                        new
                        {
                            Id = new Guid("b6f496f5-e8b0-4c9a-b3f8-a6cc2552f9c2"),
                            KweetID = "9d382436-f61d-4f8f-aca4-265c3b058488",
                            UserID = "User1"
                        });
                });

            modelBuilder.Entity("KweetService.Models.ReactionKweetModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateSend")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("KweetId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Reactions");
                });
#pragma warning restore 612, 618
        }
    }
}
