export const kweetUrl = "http://localhost:5050/kweet"
export const likeUrl = "http://localhost:5050/Like"
export const reactionUrl = "http://localhost:5050/reaction"
export const authUrl = "http://localhost:5051/Auth/"
export const kweetreadurl = "http://localhost:5053/kweetread/"
export const kweetwriteurl = "http://localhost:5050/KweetWrite/"
