export const likeUrl = "http://kwetter.com/Like"
export const reactionUrl = "http://kwetter.com/reaction"
export const authUrl = "http://kwetter.com/Auth/"
export const kweetreadurl = "http://kwetter.com/kweetread/"
export const kweetwriteurl = "http://kwetter.com/KweetWrite/"
