apiVersion: apps/v1
kind: Deployment
metadata:
  name: kweetwriteservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kweetwriteservice
  template:
    metadata:
      labels:
        app: kweetwriteservice
    spec:
      containers:
      - name: kweetwriteservice
        image: fendamear/kweetwriteservice:latest
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: kweetwriteservice-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: kweetwriteservice
  ports:
  - name: kweetwriteservice
    protocol: TCP
    port: 80
    targetPort: 80
