
name: kweetreadservice

on:
  push:
    branches: [ "main" ]
    paths:
      - Backend/Kweet/KweetReadService/**
  pull_request:
    branches: [ "main" ]
    paths:
      - Backend/Kweet/KweetReadService/**

defaults:
  run:
    working-directory: Backend

jobs:

  build:
    name: Build
    # To prevent bugs in case latest has breaking changes
    runs-on: ubuntu-20.04
    steps:
    # Checks out the code
    - name: Checkout
      uses: actions/checkout@v2

    # Sets up the .NET SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '7.0.x'
    
    # Installs the dependencies
    - name: Install dependencies
      run: dotnet restore ./Kweet/KweetReadService

    # Builds the code
    - name: Build
      run: dotnet build --no-restore ./Kweet/KweetReadService
  

  docker:
        # needs: 
        #  - test
    name: Build and push Docker images to docker hub
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
        
    - name: login to docker hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD}}
        
    - name: build and push docker image
      run: |
          cd ./Kweet/KweetReadService
          docker build -t fendamear/kweetreadservice:latest .
          docker push fendamear/kweetreadservice:latest 

#   test:
#     needs: build
#     name: Test
#     # To prevent bugs in case latest has breaking changes
#     runs-on: ubuntu-20.04
#     steps:
#     # Checks out the code
#     - name: Checkout
#       uses: actions/checkout@v2

#     # Tests the code
#     - name: Build
#       run: dotnet test ./Services/KweetService/Tests




