name: kweetWriteservice

on:
  push:
    branches: [ "main" ]
    paths:
      - Backend/Kweet/KweetWriteService/**
  pull_request:
    branches: [ "main" ]
    paths:
      - Backend/Kweet/KweetWriteService/**

defaults:
  run:
    working-directory: Backend

jobs:

  build:
    name: Build
    # To prevent bugs in case latest has breaking changes
    runs-on: ubuntu-20.04
    steps:
    # Checks out the code
    - name: Checkout
      uses: actions/checkout@v2

    # Sets up the .NET SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '7.0.x'
    
    # Installs the dependencies
    - name: Install dependencies
      run: dotnet restore ./Kweet/KweetWriteService

    # Builds the code
    - name: Build
      run: dotnet build --no-restore ./Kweet/KweetWriteService
      
  test:
    needs: build
    name: Test
    # To prevent bugs in case latest has breaking changes
    runs-on: ubuntu-20.04
    steps:
    # Checks out the code
    - name: Checkout
      uses: actions/checkout@v2

    # Tests the code
    - name: Build
      run: dotnet test ./Kweet/KweetWriteServiceTest
      
  docker:
    needs: 
     - test
    name: Build and push Docker images
    environment:
      name: docker
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build the docker image
      run: |
        echo "Building KweetService docker image"
        docker build -t ${{ secrets.KWEETWRITE_SERVICE_REGISTRY }}:latest -f ./kweet/KweetWriteService/Dockerfile .

  
      
  
