name: kweetWriteservice

on:
  push:
    branches: [ "main" ]
    paths:
      - Backend/Kweet/KweetWriteService/**
      - ../.github/**
  pull_request:
    branches: [ "main" ]
    paths:
      - Backend/Kweet/KweetWriteService/**

defaults:
  run:
    working-directory: Backend

jobs:

  # build:
  #   name: Build
  #   # To prevent bugs in case latest has breaking changes
  #   runs-on: ubuntu-20.04
  #   steps:
  #   # Checks out the code
  #   - name: Checkout
  #     uses: actions/checkout@v2

  #   # Sets up the .NET SDK
  #   - name: Setup .NET SDK
  #     uses: actions/setup-dotnet@v1.7.2
  #     with:
  #       dotnet-version: '7.0.x'
    
  #   # Installs the dependencies
  #   - name: Install dependencies
  #     run: dotnet restore ./Kweet/KweetWriteService

  #   # Builds the code
  #   - name: Build
  #     run: dotnet build --no-restore ./Kweet/KweetWriteService
      
  # test:
  #   needs: build
  #   name: Test
  #   # To prevent bugs in case latest has breaking changes
  #   runs-on: ubuntu-20.04
  #   steps:
  #   # Checks out the code
  #   - name: Checkout
  #     uses: actions/checkout@v2

  #   # Tests the code
  #   - name: Build
  #     run: dotnet test ./Kweet/KweetWriteServiceTest
      
  docker:
    # needs: 
    #  - test
    name: Build and push Docker images to docker hub
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: login to docker hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: fendamear
        password: Nickboy2023
    
    - name: build and push docker image
      run: |
         cd ./Kweet/KweetWriteService
         docker build -t fendamear/KweetWriteService:latest .
         docker push fendamear/KweetWriteService:latest 
        # docker:
        #   # needs: 
        #   #  - test
        #   name: Build and push Docker images to docker hub
        #   runs-on: ubuntu-20.04
        #   steps:
        #   - name: Checkout
        #     uses: actions/checkout@v3
          
        #   - name: login to docker hub
        #     uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        #     with:
        #       username: fendamear
        #       password: Nickboy2023
          
        #   - name: Extract metadata (tags, labels) for Docker
        #     id: meta
        #     uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        #     with:
        #       images: $ {{ secrets.KWEETWRITE_SERVICE_REGISTRY }}
          
        #   - name: Build and push Docker image
        #     uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        #     with: 
        #       context: Backend/Kweet/KweetWriteService/
        #       file: Dockerfile
        #       push: true
        #       tags: latest
  
      
  
